# Generated by Django 5.1.1 on 2024-09-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fblood', '0002_donar_signup_info_delete_donar_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donar_signup_info',
            name='email',
        ),
    ]
