# Generated by Django 5.1.1 on 2024-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblood', '0004_donar_donate_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
