# Generated by Django 5.1.1 on 2024-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblood', '0005_previousinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donar_signup_info',
            name='email',
            field=models.EmailField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
