# Generated by Django 5.1.1 on 2024-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblood', '0006_donar_signup_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donar_signup_info',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
